# Base configuration for security sensitive environments.

# Disable summary of object/key for rejected property operations.  May be
# relevant if keys contain potentially sensitive information.
DUK_USE_VERBOSE_PROP_ERRORS: false

# Disable tracebacks, minimizes attacker knowledge of call chains.  Access
# to the internal error _Tracedata property provides access to all functions
# in the call chain (even when they're otherwise not visible to sandboxed
# code).
DUK_USE_TRACEBACKS: false

# TBD
